### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by adriangalera** [jpaalasm/zephyr-bt#2]
Hello, could you provide info about how to run the tests?

I am trying to run it with:

python read_from_device.py

But I am getting errors like:

Traceback (most recent call last):
  File "read_from_device.py", line 5, in <module>
    import zephyr
ImportError: No module named zephyr

Is zephyr some kind of python module or do you define it somewhere?

Thank you

**Comment by jpaalasm** [comment]
Hi. you have to add zephyr-bt/src to PYTHONPATH or sys.path so that the package "zephyr" can be found.
